Upgrade TestGoogleAPI + add ParsedSheetToJsonConverter
vangogih/C4G pull request #15
Opened 2024-11-17 12:53 UTC by JohnnyZaev

2024-11-17 17:16 UTC, alexboost222 requested changes
Отписал в комменты пару моментов

2024-11-17 17:16 UTC, alexboost222 commented on C4G.Unity/Assets/C4G/Editor/Scripts/ParsedSheetToJsonConverter.cs
> +                        entityDict[property.Name] = entity.ElementAtOrDefault(index);
Тут бы ElementAt заюзал чтобы сразу упасть если нет элемента по индексу и не отлавливать странные багосики

2024-11-17 17:16 UTC, alexboost222 commented on C4G.Unity/Assets/C4G/Editor/Scripts/ParsedSheetToJsonConverter.cs
> +                    var entityDict = new Dictionary<string, object>();
Можно <string, string>

2024-11-17 17:16 UTC, alexboost222 commented on C4G.Unity/Assets/C4G/Editor/Scripts/ParsedSheetToJsonConverter.cs
> +        public static void ConvertParsedSheetToJson(ParsedSheet parsedSheet, string fileName)
В fileName по сути передается то же самое что уже лежит в parsedSheet.Name
Можно параметр убрать и заюзать из ParsedSheet

2024-11-17 17:16 UTC, alexboost222 commented on C4G.Unity/Assets/C4G/Editor/Scripts/TestGoogleApis.cs
> +            string secretsDirectory = Path.GetFullPath(Path.Combine(Application.dataPath, "C4G", "Editor", "Secrets"));
Можно не править
Чисто обратил внимание
Общий путь юзаешь тут и далее в Test()
Его бы сразу в отдельную переменную

2024-11-17 19:24 UTC, vangogih commented on C4G.Unity/Assets/C4G/Editor/Scripts/TestGoogleApis.cs
> +            string secretsDirectory = Path.GetFullPath(Path.Combine(Application.dataPath, "C4G", "Editor", "Secrets"));
Да, можно сразу в Constants например

2024-11-20 17:23 UTC, alexboost222 approved these changes

2024-11-20 17:24 UTC, merged